# Generated by Django 3.1.5 on 2022-01-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20211216_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='possible_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.CharField(default='', max_length=200),
        ),
    ]
